### PR TITLE
Infoboxes as mapping source

### PR DESCRIPTION
**Pull request by apohllo**
@djstrong please have a look at the implementation. Only the three last commits are relevant.

### CODE REVIEW

**Comment by djstrong** [comment]
@apohllo I merged it with master, so please review and merge pull request.
Should I change automatic code reformatting?

**Comment by apohllo** [comment]
Adjusting our code formatting styles would be good :-) The small changes are:
- no spaces after comma
- no spaces around opening curly brace

What do you thing about that?

**Comment by apohllo** [comment]
Ping me after reformatting and I will merge the pull request.

**Comment by djstrong** [comment]
Personally I like spaces after commas. Sometimes it is hard to see arguments having using dots.
However I will adapt ;) 
Moreover, both issues aren't configurable in reformatter :/

**Comment by apohllo** [comment]
Ok, let's go your way :-)

**Comment by djstrong** [comment]
Are you sure? ;) If yes then I guess you can merge.

**Pull request merged**
